import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { setAssetPath } from "@esri/calcite-components/dist/components";
import "@esri/calcite-components/dist/calcite/calcite.css";
import "./globals.css";

setAssetPath("https://unpkg.com/@esri/calcite-components/dist/calcite/assets");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					type="text/css"
					href="https://js.arcgis.com/4.27/esri/themes/dark/main.css"
				/>
			</head>
			<body className={`h-screen ${inter.className}`}>{children}</body>
		</html>
	);
}
